run-name: Deploy to yogaclassbooking API @${{ github.actor }}
on:
  push:
    branches:
      - prod-deployment
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create application.properties
        run: |
          mkdir -p src/main/resources
          echo '${{ secrets.APP_PROPERTIES }}' > src/main/resources/application-prod.properties

      - name: Verify application-prod.properties
        run: cat src/main/resources/application-prod.properties

      - name: Build the Application
        run: mvn clean install -U -DskipTests

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.REPOSITORY }}:${{ vars.API_IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-api-service:
    name: Deploy to API Service
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/deployment
            bash deploy.sh
